# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/yilel/Desktop/Exp4/Exp4.srcs/sources_1/ip/ROM_D/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yilel/Desktop/Exp4/Exp4.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/yilel/Desktop/Exp4/Exp4.srcs/sources_1/ip/ROM_D/ROM_D.xci
# IP: The module: 'ROM_D' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yilel/Desktop/Exp4/Exp4.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_D'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
