# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/yilel/Desktop/Exp6/code/constraint.xdc

# IP: ip/divider/divider.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider || ORIG_REF_NAME==divider} -quiet] -quiet

# IP: ip/multiplier/multiplier.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiplier || ORIG_REF_NAME==multiplier} -quiet] -quiet
